name: terraform-plan-prod-on-merge

on:
  pull_request:
    types:
      - closed
    branches:
      - main

jobs:
  plan-prod:
    if: ${{ github.event.pull_request.merged == true }}
    runs-on: ubuntu-latest
    concurrency: terraform-plan-prod-on-merge
    permissions:
      contents: read

    steps:
      - uses: actions/checkout@v7
        with:
          ref: ${{ github.event.pull_request.merge_commit_sha }}

      - name: Install Task
        run: sudo sh -c "$(curl --location https://taskfile.dev/install.sh)" -- -d -b /usr/local/bin

      - uses: hashicorp/setup-terraform@v4
        with:
          terraform_version: 1.9.7

      - name: Configure AWS credentials
        uses: aws-actions/configure-aws-credentials@v6
        with:
          aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
          aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          aws-region: ${{ secrets.AWS_REGION }}

      - name: Plan prod
        run: task plan-prod
